### ISSUE TITLE
Proposal: Change the validate API to static method to avoid instantiating Validator class

### ISSUE THREAD

**Issue by NumanIjaz** [NumanIjaz/steuer-id#2]
Since some of the private methods are changed to static methods, it makes sense to also change the `validate` method of class `SteuerIdValidator` a static method.

This way you won't have to instantiate the class to call the validate method.

After this change we should adjust README.md and tests as well.

**Comment by zembrowski** [comment]
Yes, I agree - all methods should be static.

And my bad, for mixing this up in the PR #1.

**Comment by NumanIjaz** [comment]
In that case, I will implement this in another commit.
